import{a as w,S as b,i}from"./assets/vendor-CFFvTae-.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const P="56433507-28871935314b081e8c424dd0b";async function u(o,s){return(await w.get("https://pixabay.com/api/",{params:{key:P,q:o,image_type:"photo",page:s,per_page:15,orientation:"horizontal",safesearch:!0}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".loader-btn"),S=new b(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const s=o.map(t=>`
        <li class="items-list">
            <a href="${t.largeImageURL}">
              <img src="${t.webformatURL}" class="img" alt="${t.tags}"/>
            </a>
          <div class="hits-p">
            <p>Likes:${t.likes}</p>
            <p>Views:${t.views}</p>
            <p>Comments:${t.comments}</p>
            <p>Downloads:${t.downloads}</p>
          </div>
        </li>`).join("");f.insertAdjacentHTML("beforeend",s),S.refresh()}function q(){f.innerHTML=""}function g(){m.classList.remove("hidden")}function p(){m.classList.add("hidden")}function L(){h.classList.remove("hidden")}function c(){h.classList.add("hidden")}const v=document.querySelector(".form"),E=document.querySelector(".loader-btn");let d="",a=1;v.addEventListener("submit",async o=>{o.preventDefault();const s=o.currentTarget,n=new FormData(s).get("search-text").trim();if(n===""){i.error({title:"Error",message:"Pleas enter a search query"});return}d=n,a=1,q(),c(),g();try{const e=await u(d,a);if(e.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}y(e.hits);const r=Math.ceil(e.totalHits/15);a<r?L():c(),s.reset()}catch(e){i.error({title:"Error",message:"Something went wrong. Please try again later!"}),console.log(e)}finally{p()}});E.addEventListener("click",async()=>{a+=1,c(),g();try{const o=await u(d,a);y(o.hits);const{height:s}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"});const t=Math.ceil(o.totalHits/15);a<t?L():(c(),i.info({message:"We're sorry, but you've reached the end of search results."}))}catch(o){i.error({title:"Error",message:"Something went wrong Please try again later!"}),console.log(o)}finally{p()}});
//# sourceMappingURL=index.js.map
