import{a as w,S as b,i as a}from"./assets/vendor-CFFvTae-.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const v="56433507-28871935314b081e8c424dd0b";async function u(o,s){return(await w.get("https://pixabay.com/api/",{params:{key:v,q:o,image_type:"photo",page:s,per_page:15,orientation:"horizontal",safesearch:!0}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".loader-btn"),P=new b(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const s=o.map(t=>`
        <li class="items-list">
            <a href="${t.largeImageURL}">
              <img src="${t.webformatURL}" class="img" alt="${t.tags}"/>
            </a>
          <div class="hits-p">
            <p>Likes:${t.likes}</p>
            <p>Views:${t.views}</p>
            <p>Comments:${t.comments}</p>
            <p>Downloads:${t.downloads}</p>
          </div>
        </li>`).join("");f.insertAdjacentHTML("beforeend",s),P.refresh()}function S(){f.innerHTML=""}function g(){m.classList.remove("hidden")}function p(){m.classList.add("hidden")}function L(){h.classList.remove("hidden")}function c(){h.classList.add("hidden")}const q=document.querySelector(".form"),E=document.querySelector(".loader-btn");let d="",n=1;q.addEventListener("submit",async o=>{o.preventDefault();const s=o.currentTarget,i=new FormData(s).get("search-text").trim();if(i===""){a.error({title:"Error",message:"Pleas enter a search query"});return}d=i,n=1,S(),c(),g();try{const e=await u(d,n);if(e.hits.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}y(e.hits);const r=Math.ceil(e.totalHits/15);n<r?L():(c(),a.info({message:"We're sorry, but you've reached the end of search results."})),s.reset()}catch(e){a.error({title:"Error",message:"Something went wrong. Please try again later!"}),console.log(e)}finally{p()}});E.addEventListener("click",async()=>{n+=1,c(),g();try{const o=await u(d,n);y(o.hits);const{height:s}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"});const t=Math.ceil(o.totalHits/15);n<t?L():(c(),a.info({message:"We're sorry, but you've reached the end of search results."}))}catch(o){a.error({title:"Error",message:"Something went wrong Please try again later!"}),console.log(o)}finally{p()}});
//# sourceMappingURL=index.js.map
