import{a as w,S as b,i}from"./assets/vendor-CFFvTae-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const P="56433507-28871935314b081e8c424dd0b";async function u(r,o){return(await w.get("https://pixabay.com/api/",{params:{key:P,q:r,image_type:"photo",page:o,per_page:15,orientation:"horizontal",safesearch:!0}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".loader-btn"),E=new b(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const o=r.map(s=>`
        <li class="items-list">
            <a href="${s.largeImageURL}">
              <img src="${s.webformatURL}" class="img" alt="${s.tags}"/>
            </a>
          <div class="hits-p">
            <p>Likes:${s.likes}</p>
            <p>Views:${s.views}</p>
            <p>Comments:${s.comments}</p>
            <p>Downloads:${s.downloads}</p>
          </div>
        </li>`).join("");f.insertAdjacentHTML("beforeend",o),E.refresh()}function S(){f.innerHTML=""}function p(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function L(){y.classList.remove("hidden")}function c(){y.classList.add("hidden")}const q=document.querySelector(".form"),v=document.querySelector(".loader-btn");let d="",a=1;q.addEventListener("submit",async r=>{r.preventDefault();const o=r.currentTarget,n=new FormData(o).get("search-text").trim();if(n===""){i.error({title:"Error",message:"Pleas enter a search query"});return}d=n,a=1,S(),c(),p();try{const e=await u(d,a);if(e.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}h(e.hits);const t=Math.ceil(e.totalHits/15);a<t?L():c(),o.reset()}catch(e){i.error({title:"Error",message:"Something went wrong. Please try again later!"}),console.log(e)}finally{g()}});v.addEventListener("click",async()=>{a+=1,c(),p();try{const r=await u(d,a);h(r.hits);const o=Math.ceil(r.totalHits/15);a<o?L():(c(),i.info({message:"We're sorry, but you've reached the end of search results."}))}catch(r){i.error({title:"Error",message:"Something went wrong Please try again later!"}),console.log(r)}finally{g()}});
//# sourceMappingURL=index.js.map
